### PR TITLE
Fix whitelisting for URLs with non-root base path.

### PR DESCRIPTION
**Pull request by vanam**

### CODE REVIEW

**Comment by f3l1x** [comment]
It is failing, right?

**Comment by vanam** [comment]
Yes, I have to find a better way how find basePath. I created issue prematurely.

**Comment by vanam** [comment]
[Using middleware](https://github.com/contributte/middlewares/tree/master/.docs#autobasepathmiddleware) is more elegant.

**Comment by f3l1x** [comment]
Thanks.

**Pull request merged**
