### PR TITLE
Add REST API documentation.

### PR DESCRIPTION
**Pull request by vanam**
[SwaggerUI](https://github.com/swagger-api/swagger-ui) + [Feeling Blue](https://github.com/ostranme/swagger-ui-themes) theme

### CODE REVIEW

**Comment by f3l1x** [comment]
Hi. Thx for your PR. This is big change. What is your motivation to use it like that?

**Comment by vanam** [comment]
Every API should have some kind of documentation. This way I deploy API with documentation UI. (There are [frameworks/libraries](https://quarkus.io/guides/openapi-swaggerui) which do it like this).

Feel free not accept this change if you don't like it. However, I use it this way and I thought it might be usefu for others.

It is not perfect (you have to manually update the UI).

**Comment by f3l1x** [comment]
I like it, I really do, but I use different doc generate. Other folks might also use different ones. Could you please rewrite doc manual for others? I think it would be better way.

**Comment by vanam** [comment]
I am confused. What do you want me to do? Add some info to README?

OpenAPI specification is generated from code and available at `/api/public/v1/openapi/meta`. I just added UI for that. We can argue if SwaggerUI is the best options (I quite like [ReDoc](https://github.com/Redocly/redoc)) and why use theme Feeling Blue (I like how it looks).

**Comment by f3l1x** [comment]
I don't want to include any OpenAPI GUI client. But, it could be great to have a user guide how to include it to the project. Just simple steps, where to download, how to configure.

**Comment by vanam** [comment]
I got rid off the UI.

**Comment by f3l1x** [comment]
Awesome! ❤️

**Pull request merged**
