### PR TITLE
fix: don't flush users in every iteration

### PR DESCRIPTION
**Pull request by VottusCode**
Calling the flush() only once so all random users are flushed in one transaction.

### CODE REVIEW

**Comment by f3l1x** [comment]
Thx. Similar to https://github.com/contributte/webapp-skeleton?

**Comment by VottusCode** [comment]
Done.

**Comment by VottusCode** [comment]
> Also, why not just have getStaticUsers() return User[], that way we can have one foreach and can get rid of the saveUser function.

obrazek

**Comment by f3l1x** [comment]
It's for education. I think it's fine as it is.

**Comment by VottusCode** [comment]
> It's for education. I think it's fine as it is.

Fari point, although people tend to just go along with the template and they don't even consider that there's a better way.

**Pull request merged**
